export const SUPPORTED_LANGUAGES = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇬🇧' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', flag: '🇮🇳' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' }
];

export const DEFAULT_LANGUAGE = 'en';

export const UI_TRANSLATIONS = {
  en: {
    appTitle: 'IP-SAKTI Sahayak',
    appSubtitle: 'Multilingual AI Knowledge Assistant for Intellectual Property',
    devBadge: 'DEVELOPMENT PROTOTYPE',
    disclaimerBanner: 'PROTOTYPE DEMONSTRATION: Research & development model. Document corpus is in development. Answers are simulated from draft knowledge artifacts and do not constitute official legal advice.',
    newChat: 'New Chat',
    chatHistory: 'Chat History',
    noHistory: 'No prior sessions recorded.',
    categoriesTitle: 'Domain Knowledge Hub',
    searchPlaceholder: 'Ask an IP question in English, मराठी, or हिन्दी... (e.g. Patent filing documents)',
    sendButton: 'Send',
    generating: 'Generating response from knowledge corpus...',
    stopGenerating: 'Stop Generation',
    sourcesHeading: 'Authoritative Sources & Citations',
    pageLabel: 'Page',
    sectionLabel: 'Section',
    viewOfficialDoc: 'Verify Source Document',
    copyAnswer: 'Copy Answer',
    copied: 'Copied!',
    retry: 'Retry Request',
    noSourcesTitle: 'General Guidance (No Direct Source Citation)',
    noSourcesDesc: 'This answer was synthesized from general regulatory knowledge. No specific statutory section passed high-confidence retrieval threshold.',
    welcomeTitle: 'Welcome to IP-SAKTI Sahayak',
    welcomeDesc: 'Your unified AI intelligence assistant for Patents, Trademarks, Copyright, Designs, GI, Toys/BIS, and Ayush TKDL.',
    exploreCategories: 'Explore Specialized Knowledge Domains',
    suggestedQueries: 'Sample Queries for Testing',
    devSettings: 'API / RAG Settings',
    mockModeActive: 'Mock Mode Active',
    liveApiActive: 'Live Backend Connected'
  },
  mr: {
    appTitle: 'आयपी-शक्ती सहायक',
    appSubtitle: 'बौद्धिक संपदा बहुभाषिक एआय सहाय्यक',
    devBadge: 'प्रोटोटाइप विकास टप्पा',
    disclaimerBanner: 'प्रोटोटाइप प्रात्यक्षिक: संशोधन आणि विकास मॉडेल. अंतिम दस्तऐवज संचलन प्रक्रियेत आहे. उत्तरे केवळ नमुना डेटावर आधारित आहेत, अधिकृत कायदेशीर सल्ला नाही.',
    newChat: 'नवीन संभाषण (New Chat)',
    chatHistory: 'मागील संभाषणे',
    noHistory: 'कोणतीही मागील संभाषणे उपलब्ध नाहीत.',
    categoriesTitle: 'बौद्धिक संपदा विभाग',
    searchPlaceholder: 'मराठी, हिंदी किंवा इंग्रजीत प्रश्न विचारा... (उदा. पेटंट अर्जासाठी कोणती कागदपत्रे लागतील?)',
    sendButton: 'पाठवा',
    generating: 'दस्तऐवजांमधून उत्तर शोधत आहे...',
    stopGenerating: 'थांबवा',
    sourcesHeading: 'अधिकृत संदर्भ आणि दस्तऐवज (Sources)',
    pageLabel: 'पृष्ठ',
    sectionLabel: 'कलम / विभाग',
    viewOfficialDoc: 'अधिकृत दस्तऐवज तपासा',
    copyAnswer: 'उत्तर कॉपी करा',
    copied: 'कॉपी झाले!',
    retry: 'पुन्हा प्रयत्न करा',
    noSourcesTitle: 'सामान्य मार्गदर्शन (थेट संदर्भ उपलब्ध नाही)',
    noSourcesDesc: 'हे उत्तर सामान्य नियम संचावर आधारित आहे. विशिष्ट कलमाचा उच्च खात्रीशीर संदर्भ आढळला नाही.',
    welcomeTitle: 'आयपी-शक्ती सहायकमध्ये आपले स्वागत आहे',
    welcomeDesc: 'पेटंट, ट्रेडमार्क, कॉपीराइट, डिझाईन, जीआय, बीआयएस आणि आयुष साठी आपले विश्वसनीय एआय मार्गदर्शक.',
    exploreCategories: 'महत्त्वाचे विभाग एक्सप्लोर करा',
    suggestedQueries: 'चाचणीसाठी नमुना प्रश्न',
    devSettings: 'एपीआय / रॅग सेटिंग्ज',
    mockModeActive: 'मॉक मोड सक्रिय',
    liveApiActive: 'थेट बॅकएंड कनेक्टेड'
  },
  hi: {
    appTitle: 'आईपी-शक्ति सहायक',
    appSubtitle: 'बौद्धिक संपदा बहुभाषी एआई ज्ञान सहायक',
    devBadge: 'प्रोटोटाइप विकास चरण',
    disclaimerBanner: 'प्रोटोटाइप प्रदर्शन: अनुसंधान एवं विकास मॉडल। अंतिम दस्तावेज संकलन प्रगति पर है। उत्तर केवल परीक्षण डेटा पर आधारित हैं, आधिकारिक कानूनी सलाह नहीं है।',
    newChat: 'नई बातचीत (New Chat)',
    chatHistory: 'बातचीत का इतिहास',
    noHistory: 'कोई पूर्व सत्र उपलब्ध नहीं है।',
    categoriesTitle: 'बौद्धिक संपदा श्रेणियां',
    searchPlaceholder: 'हिन्दी, मराठी या अंग्रेजी में प्रश्न पूछें... (उदा. पेटेंट आवेदन के लिए आवश्यक दस्तावेज)',
    sendButton: 'भेजें',
    generating: 'दस्तावेज कोष से उत्तर तैयार किया जा रहा है...',
    stopGenerating: 'रोकें',
    sourcesHeading: 'प्रामाणिक स्रोत और संदर्भ (Sources)',
    pageLabel: 'पृष्ठ',
    sectionLabel: 'धारा / अनुभाग',
    viewOfficialDoc: 'आधिकारिक स्रोत देखें',
    copyAnswer: 'उत्तर कॉपी करें',
    copied: 'कॉपी हो गया!',
    retry: 'पुनः प्रयास करें',
    noSourcesTitle: 'सामान्य मार्गदर्शन (प्रत्यक्ष संदर्भ उपलब्ध नहीं)',
    noSourcesDesc: 'यह उत्तर सामान्य नियामक ज्ञान पर आधारित है। कोई विशिष्ट वैधानिक खंड उच्च आत्मविश्वास सीमा को पार नहीं कर सका।',
    welcomeTitle: 'आईपी-शक्ति सहायक में आपका स्वागत है',
    welcomeDesc: 'पेटेंट, ट्रेडमार्क, कॉपीराइट, डिजाइन, जीआई, बीआईएस खिलौना मानक एवं आयुष के लिए आधिकारिक एआई सहायक।',
    exploreCategories: 'विशिष्ट ज्ञान श्रेणियों का अन्वेषण करें',
    suggestedQueries: 'परीक्षण के लिए सुझाए गए प्रश्न',
    devSettings: 'एपीआई / रैग सेटिंग्स',
    mockModeActive: 'मॉक मोड सक्रिय',
    liveApiActive: 'लाइव बैकएंड कनेक्टेड'
  }
};
